version: "3.9"

services:

  timescaledb:
    build:
      context: ./timescaledb
    volumes:
      - timescaledb-data:/Users/jonatasdp/code/timescale/opentelemetry-demo
    ports:
      - 5999:5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  promscale:
    image: "timescale/promscale:0.8.0"
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    restart: on-failure
    depends_on:
      - timescaledb
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@timescaledb:5432/postgres?sslmode=allow
      PROMSCALE_ENABLE_FEATURE: tracing
      PROMSCALE_OTLP_GRPC_SERVER_LISTEN_ADDRESS: 0.0.0.0:9202

  jaeger:
    image: jaegertracing/jaeger-query:1.30
    ports:
      - 16685:16685/tcp
      - 16686:16686/tcp
      - 16687:16687/tcp
    restart: on-failure
    depends_on:
      - promscale
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
      GRPC_STORAGE_SERVER: promscale:9202

  grafana:
    build:
      context: ./grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    restart: on-failure
    depends_on:
      - timescaledb
      - jaeger

  collector:
    build:
      context: ./collector
    ports:
      - 4317:4317/tcp
      - 4318:4318/tcp
    restart: on-failure
    depends_on:
      - promscale

  upper:
    build:
      context: ./upper
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5054:5000/tcp

  lower:
    build:
      context: ./lower
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 4567:5000/tcp

  special:
    build:
      context: ./special
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5052:5000/tcp
  
  digit:
    build:
      context: ./digit
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5051:5000/tcp

  generator:
    build:
      context: ./generator
    restart: on-failure
    depends_on:
      - upper
      - lower
      - special
      - digit
    ports:
      - 5050:5000/tcp

  load:
    build:
      context: ./load
    restart: on-failure
    depends_on:
      - generator
    deploy:
      mode: replicated
      replicas: 3

volumes:
  timescaledb-data:
  grafana-data:
